[theme]
primaryColor = "#57d38c"
backgroundColor = "#070A12"
secondaryBackgroundColor = "#0B1630"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
port = 8502
# Enable CORS to allow requests from the HTTPS domain
enableCORS = false
# Disable XSRF protection when behind reverse proxy
enableXsrfProtection = false

[browser]
gatherUsageStats = false
